### ISSUE TITLE
Prolems with Xunit.DependencyInjection

### ISSUE THREAD

**Issue by fredericbirke** [ttutisani/Xunit.Gherkin.Quick#100]
After creating a vanilla project that includes both Xunit.Gherkin.Quick and Xunit.DependencyInjection, Xunit.Gherkin.Quick throws an ArgumentNullException.

```
System.ArgumentNullException : Value cannot be null. (Parameter 'testOutputHelper')
  Exception doesn't have a stacktrace
```

This seems to be caused in Xunit.Gherkin.Quick.ScenarioOutput line 20.
![image](https://user-images.githubusercontent.com/9481836/80290935-6aa85300-8749-11ea-80de-70fb8b7a6faf.png)

In any c# class of the project I can inject the testOutputhelper just fine, any idea whats wrong here?

Minimal reproduction example can be found here:
https://github.com/fredericbirke/gherkin-bug

**Comment by ttutisani** [comment]
Hi @fredericbirke,

Sorry for the delayed response!

I looked into your sample solution. The problem is that you are trying to define a custom test framework in `Startup.cs` file, on line 8:

![image](https://user-images.githubusercontent.com/18409870/80658201-81a1ba80-8a53-11ea-9782-7422057cefff.png)

If you comment out that line, the test starts working just fine.

I hope this helps! If not, let me know if you have further questions or comments.

**Comment by ttutisani** [comment]
I am assuming that the issue did not persist since I have not heard back. Closing the issue.
