### ISSUE TITLE
KeyWordAttributeBase inheriting from Xunit.FactAttribute

### ISSUE THREAD

**Issue by ChristianPejrup** [ttutisani/Xunit.Gherkin.Quick#11]
Both ScenarioAttribute and KeyWordAttributeBase inherits from the Xunit.FactAttribute, this means that both the individual steps and the scenario gets picked up by the test runner and displayed in the Test Explorer.

The individual steps are instantiated and invoked in Feature.cs which means that the relationship between KeyWordAttributeBase and FactAttribute does not seem important. 

I did a small test where is changed 
```
public abstract class KeyWordAttributeBase : FactAttribute
```

to just use the Attribute type
```
public abstract class KeyWordAttributeBase : Attribute
```

The Scenario seems to run fine and the upside is that Steps no longer show up in the Test Explorer.

**Comment by ttutisani** [comment]
But didn't you receive a warning saying that those methods should be decorated with Fact attribute?

You are right that the relationship is not important. And I managed to not show the step methods in the test explorer by creating a `ignore` discoverer. I thought that should do it.

Also, I was never able to reproduce showing steps in the test explorer. I only see a scenario. So I wonder if you are doing it differently than I do.
Can you explain how to reproduce?

**Comment by ChristianPejrup** [comment]
When i clean and rebuild the entire solution the individual steps show up in the Visual Studio Test Explorer (VS 2017) - i have not given it a go with ReSharper.

When i change from FactAttribute to Attribute i don't get any warnings (over all at 0 for the entire solution).

**Comment by ttutisani** [comment]
That's interesting. I never saw steps in the test explorer so far. Only scenarios. And I don't use resharper.
Anyway, if you don't see the warning, then the change should be fine.
I was seeing warning though. I guess that was about Xunit not wanting to run scenario from the class which had no fact methods in it.

So, please confirm this: if you derive from attribute instead of fact, are you able to still run the tests fine?
If so, please do the PR. That means it should be fine.
But before merge, I will pull down the PR and will check locally, just to ensure we're not introducing a side effect with warning.

**Comment by ChristianPejrup** [comment]
I ran the full test in Debug mode and every steps gets executed as expected.

Its strange that you dont experience the same behavior as i do with the test steps (i had the expected behavior when opening the project the first time - but after a rebuild i get steps along side the scenario)

**Comment by ChristianPejrup** [comment]
I will go ahead and close this issue as the PR have been closed
