### ISSUE TITLE
Has anyone got it work in a Unity3d project? - HelpWanted

### ISSUE THREAD

**Issue by Enough7** [ttutisani/Xunit.Gherkin.Quick#116]
Unfortunately Unity autogenerates the `.csproj` files so any changes get overwritten. I wonder does anybody know how to get this work?

**Comment by ttutisani** [comment]
Changes that are in the csproj file of the test project include references to the Nuget packages and "copy to output directory" setting for the .feature files. I can't think of anything else that is in the csproj file and thus can be lost during overwriting process. Can you please confirm that I understood the problem correctly?

If so, perhaps one way would be to keep the test project outside of the unity IDE. After all, the test project needs to reference your other projects and not the other way around. And you can execute the tests via command line or via visual studio (opening the test project from the visual studio directly instead of double-clicking it from inside the unity IDE). Does this help?

I don't have the unity IDE installed at the moment on my machine, so I cannot suggest anything else myself. I hope others can help.

**Comment by Enough7** [comment]
The problem basically is that I can not use my `.csproj` file because unity manages it. `Unity` offers only a Assembly definition file `.asmdef` which one can manipulate. I got a Xunit-Test running, but the feature test does not work. Its said in the readme the filename does not matter maybe I should change the file extension from `.feature` to `.cs` so the Testrunner compiles it.

**Comment by ttutisani** [comment]
If you change it to .cs, it won't compile because the content is not c#, it's gherkin. So, no, don't change it.

From what you described, it compiles but does not find feature tests (scenarios) to run. Does it allow to mark the feature file as a content, or to copy to the output directory? Can you check if the feature files are actually in the output directory? Basically, goal is to get those files into the test output directory. For clarity, when test executes from visual studio, the compiler puts everything in the output directory (dll files, exe files, and even feature files since they need to be marked as for output - this is mentioned in the readme of Xunit.Gherkin.Quick).

So, once the feature file is in the output directory, you need to see where it is, and specify the path to it correctly via the FeatureFile attribute that you attach on top of the Feature class with steps.

**Comment by Enough7** [comment]
I am probably to much of a C#-newbe to find that out 😢

**Comment by ttutisani** [comment]
¯\_(ツ)_/¯

Let's keep this issue ticket open. Maybe somebody else has already used Xunit.Gherkin.Quick with Unity and can provide a detailed answer.

**Comment by Enough7** [comment]
Someone told me to use `Directory.Build.props` to add an `ItemGroup`  to the generated files

**Comment by ttutisani** [comment]
Did that work out well?

**Comment by Enough7** [comment]
My new approach is to write a class library and import it into unity. I got the example in the ReadMe up and running with  TargetFramework netcoreapp3.1. Unfortunately unity does not support netcore only [netframework 2 or 4](https://docs.unity3d.com/2019.3/Documentation/Manual/dotnetProfileSupport.html). So I tried to get the example running in netframework 4.2 but I failed. Am I missing something is netframework different from net as it says in the ReadMe I thought it's the "same".

**Comment by Enough7** [comment]
I use Jetbrains Rider-IDE. It has a GUI for UnitTests. 
![Screenshot (219)](https://user-images.githubusercontent.com/30051680/117979825-9d60c180-b333-11eb-8f2c-756cdb5dd398.png) I press the Play button below the hammer icon. But than the tests just disappear in the UnitTestExplorer:
![Screenshot (218)](https://user-images.githubusercontent.com/30051680/117980127-ea449800-b333-11eb-8fbc-0e1df1efc4ce.png)
That happened before when in my core-try - project the feature-file-attribute had a invalid path. Thank you about the .Net lesson much appreciated :)

**Comment by Enough7** [comment]
Status: I got it up and running. I set the TargetFramework in my `Tests.csproj` to `netcoreapp3.1` and in my `NetCoreExample.csproj` I set the TargetFramework to `netstandard2.0`. I packed a NuGet-Package extracted the .dll from it and imported it in my unity-project. It seems like it works.

**Comment by ttutisani** [comment]
Very good. Please close this issue as a confirmation that your issue is resolved.

Thank you for reporting both the problem and the solution too! It will help others and myself.

**Comment by Enough7** [comment]
I was not sure. My issue is solved but the issue making it work in unity not, but I guess it is the best solution right now
