### ISSUE TITLE
Pass string as list

### ISSUE THREAD

**Issue by Enough7** [ttutisani/Xunit.Gherkin.Quick#118]
Hey,
consider the following code:

```Gherkin
Scenario: <...>
    Given A graph with Nodes named A, B, C, D
```
Is it possible to pass `A, B, C, D` as a `List<string>`? Like so:
```c#
[Given(@"A graph with Nodes named <magic regex>")]
public void AGraphWithNodesNamed(string nodeNames)
{
    ...
}
```

**Comment by ttutisani** [comment]
You should write the regex expression that will match "A, B, C, D" or whatever. The entire, comma-separated values will be matched as one string, which will be in the `nodeNames` variable when the method executes.

Have a look at [this page](https://github.com/ttutisani/Xunit.Gherkin.Quick/blob/master/docs/step-attributes.md) for examples of various regexes. You can look up online the examples of matching comma-separated values.

Note that you cannot have a `List<string>` argument in the method. This is not currently supported. Only primitive types can be used for the arguments.

After some thought, maybe you can use [DataTable as an argument](https://github.com/ttutisani/Xunit.Gherkin.Quick/blob/master/docs/datatable-argument.md), which is supported. So, instead of passing it as comma-separated values, you will write it as a table in the feature file, and you will receive it in the DataTable argument, which has rows. So each value will be on a new row.

**Comment by Enough7** [comment]
Thank you! Do you mind if I add some of this information to the readme?

**Comment by ttutisani** [comment]
I don't mind. Please add where you expected to find this information, and others will find it there in the future.

Thank you!
