### ISSUE TITLE
Shared steps for features

### ISSUE THREAD

**Issue by ChristianPejrup** [ttutisani/Xunit.Gherkin.Quick#14]
# Synopsis
On my team we use Specflow/Gherkin tests to describe the various white box test of our services.

The tests are perfect for release documentation as we can map them one to one to the release documentation/protocol we need to satisfy with every software update.

The tests are very comprehensive and can some times span multiple services to enable testing of the last link in a long chain of events.

One of the key functionalities we use is sharing steps between different features.

eg. most of the tests will start by authenticating with username and password before progressing to the next step in the process.

# Specflow
Specflow has a implementation that is parsed along with every scenario that allows for grouping and sharing important information - namely the ScenarioContext.

# Solutions

- Some kind of constructor injection
- Some implementation that relied on [xUnit shared context](https://xunit.github.io/docs/shared-context)

_There are probably other options - but something more native to xUnit is probably the best solution._

Please share any suggestions - or if you dont feel like this belongs in the package at all.

**Comment by ttutisani** [comment]
Before solutioning this, I was wondering: can't this be solves using inheritance?
You can have a base class with shared steps, derive that from `Feature`, and then derive all the concrete feature classes from that, to reuse the steps.
Thoughts?

**Comment by ChristianPejrup** [comment]
I'm sure this can be solved inheritance - i did specifically omit that solution as it feels like a forced relationship "favor composition over inheritance".

I'm mainly asking if you feel like there could be a place for a first class concept similar to what they have in Specflow. Even though it might be in contradiction to the Quick part of the Libraries name.

When looking at the Specflow framework it feels the unit test frameworks have been added on top of Specflow as oppose to xUnit.Gherkin.Quick where support for Gherkin is added on top of a existing framework. The last one feels more natural and will grow natively as xUnit grows.

**Comment by ttutisani** [comment]
My first answer to this would be: "Quick" framework should only support features which are not otherwise achievable, or are considered essential to "BDD with Gherkin" approach as such.

Also, this is an interesting topic in general. While I also prefer composition over inheritance, maybe not necessarily in this case. With composition, you would need to call methods on the injected interface. While with inheritance you compose steps using Gherkin feature file itself. So there is no overhead of code which explicitly calls the injected interface methods.
So, with all this in mind, I think inheritance makes more natural feeling in this specific case.

Also, from concept standpoint. As we know, composition is "can do", while inheritance is "is a" relationship. In this case, the relationship definitely falls under "is a" relationship naturally.
e.g. base class can be `CalculatorFeature`, while derived classes can be `BasicCalculatorFeature` and `ScientificCalculatorFeature` respectively. You would agree that both derived classes in this case "are" still concrete cases of the Calculator feature.
Composition would make them sound like "can do", which I don't think is the case with scenario step reuse.

So, I'd restrain from implementing this for now. But we need to see if there are other supporters for this and for what reasons.

**Comment by ChristianPejrup** [comment]
I completely agree in the calculator example - it is very natiral relationship.
In my example it does feel like the scope is bigger, it’s more like having a house class that ingerits from a lock class 😏

It still feels a bit premature which is why i opened it more as a discussion topic looking for some kind of input.

In regards to the Quick part i still think this project has a lot of potential that might take it beyond the quick part...

Should i keep the issue open or just go ahead and close it - create a now if it becomes relevant?

**Comment by ttutisani** [comment]
Let's keep it open. I'm curious to see what other newcomers will have to say about it.

**Comment by csurfleet** [comment]
This will probably become clearer as it becomes used on larger projects. We're already using this at work, but I've only got around 15 specs in that project - as that figure increases I'll play around with various ways of organising things and report back. Inheritance does seem the natural way forward, at least for me - its very similar to how I structure my unit/integration tests - one or more base classes that the unit test classes inherit.

**Comment by laneser** [comment]
for the ScenarioContext issues, I simply add the class to resolve the problem.
Although the the ScenarioContext's is now shared for all unit-test process.

```
    public class ScenarioContext
    {
        public static Dictionary<string, object> Current = new Dictionary<string, object>();
    }
```

**Comment by csurfleet** [comment]
After using this for a good while now, we're quite happy using inheritance as shared, I don't think shared steps is required as a feature in its own right

**Comment by ttutisani** [comment]
Thanks for the feedback @csurfleet !
This issue has been inactive for quite some time. I will close it with this all info in it. I hope that people coming to this issue will find the right answers. If not, I will hear about it anyway.
Cheers!
