### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by ChristianPejrup** [ttutisani/Xunit.Gherkin.Quick#15]
@ttutisani What is your plans for release(s) and scope?

**Comment by ChristianPejrup** [comment]
Sorry i's not sure this is the right way to ask this question - but couldn't really find a personal message feature and didn't want to resort to social media stalking...

**Comment by ttutisani** [comment]
This is the right way. That's why I created a Discussion label. You can always use that to start any discussion.

So, my plan is to release next minor version (1.1) with the backwards compatible increment. Most likely it will include the test output and table data support in it.

In general, I'm letting it flow by itself. Only thing that I'm constraining right now is the versioning scheme:
- Major version for non-backwards compatible release.
- Minor version for backwards compatible with the last major version release.
- And third version number for the bug fixes (I hope there will be no bugs).

Do you agree/disagree? thoughts?

**Comment by ChristianPejrup** [comment]
And completely agree with your thoughts about v1.1.0, these are changes that most people probably can't live with out.

Maybe for the sake of transparency maybe create a milestone v1.1.0 that includes the two tasks you mentioned. I personally love it when a project have a well defined list of priorities. Even if there are no active milestones - its just an indication that no feature development is in progress.

Regarding versioning I think the general rule of thumb is to follow [SemVer](https://semver.org/), which is basically what you outlined above.

So i guess i agree on all of the above.

**Comment by ttutisani** [comment]
I would create a milestone, but I don't want to set the scope in stone. 1.1 will include those features "_most likely_", as I said before. It can include something more or less.
I don't think it's so important what it includes. As long as it's a preferably working increment, we can have it released even now. Well, it's not in the state that I want to release (due to constructor param which I hoped I would be able to avoid, but was not sure for some time). Once it's in a preferred working state, I will release right away.
I know it may be slightly different than how people think about releases and milestones though.

Basically, for me a milestone is a stopper rather than enabler. Instead, I want to think about it as a continuous flow, which is always in a "release anytime" state. That can be easily enabled by properly doing 2 things:
1. Continuous integration - we have that.
2. Work on and merge small but correctly working and non-breaking features.

So, at the end, you have a master branch which can be taken and released at any time. And that also means that at any time, we can have a feature development in progress, which was considered a priority at that time. Small features make this easy too.
I think this is too good to give up for the milestone. But I can be convinced back if there are benefits that I'm missing, except project management or something like that. Agile flows always have won so far.

**Comment by ChristianPejrup** [comment]
I understand the reluctance to the very hard scope's that use come from defining Milestones with a well defined feature set - its not very agile, and Agile >Arbitrary release schedule...

I think my affinity for Milestones is that they naturally indicate when a major step in a projects lifecycle have been achieved. Having a milestone v1.1 is not very useful anyway as it doesn't really describe a "big step" in any direction.
A milestone to "support the basic concepts of the Gherkin" might be more correct and indicate to people who are interested in good quick overview of the project state. In a milestone it would be natural to have multiple minor version releases (whenever a new feature have been completed like the Gherkin table support).

My interest in this area of a project is mostly giving my self and others a good overview of the projects direction. I'm interested in depending on the project but is it ready for me? With my knowledge of the project I would start using this project once Test Output have been supported (Tables is a really neat feature unfortiunetly I often find that people go out of their way to formulate generic steps that give little to no insights into what they are actually doing to enable the use of tables).

**Comment by csurfleet** [comment]
I tend to fall on the 'small, regular releases' rather than milestones side of things. So long as there are issues getting resolved, and the versioning stays semantic so people can rely on it then we're all good.

Are there any major new features you're thinking about a milestone being centred around?

**Comment by ChristianPejrup** [comment]
Not really - like I mentioned the suggestion was mainly to establish some transparency about what had priority and why, the same could be achieved with some priority labels I personally find it more easy to get a quick overview of a project by taking a look at releases or milestones as I find it a good tool for framing groups of changes.

Also like I wrote above there is nothing preventing you from doing multiple smaller releases inside the scope of a milestone. I personally favour the smaller releases as it gives a lot more value to get changes out when they are done to gather some quick feedback while changes are still fresh in memory. Bugs or bad design is more easy to address when you have not build multiple months worth of changes on top of them :-)

**Comment by ttutisani** [comment]
Yeah, I see the value in milestones as defining the project roadmap, indeed. I can see how that can help people set their expectations realistically.
On this project, I did never have any roadmap in mind. I started it when I realized there was no good gherkin support for .net core. I wanted to have it quickly done and used, which I did. I use it on my other project and I'm happy with it.
I did think about the ways the project would grow, and that was mainly based on consumers feedback, just like how we do it now. People need things, they open issues, and if it seems important or natural to be included (e.g. table data, which is part of Gherkin anyway so of course should be supported), or if it seems important and users would love (e.g. output mentioning steps), then it would be implemented, either by me or others.
So far we are doing exactly as I had envisioned this process. Lightweight and purely based on consumers feedback.
But I do see value in setting expectations for future releases. I hope that we'll start doing that when the project naturally matures into that size (e.g. if we have many issues pending and the need of prioritization emerges). Until then, I love that we are driven completely based on feedback. Not everybody can afford that :-)

**Comment by ttutisani** [comment]
Meanwhile, to have some transparency (which is a good word), I'm thinking to have a readme file for the accomplished scope, for each release. Basically, release notes, which will be either describing a past release (e.g. 1.0), or future release candidate (e.g. 1.1). For the past release, it simply lists features that were released into that version. For the future release, it will mention features that are candidates for the release so far (because they are merged but version is not yet released). When the version is released, the future release readme simply becomes the release notes document with minor change (maybe title will not say RC anymore).

How is this as a trade-off?

**Comment by ChristianPejrup** [comment]
I think it is a good trade off. Please don’t see this as criticism of your work - i love the work you have done here, the achivement of Gherkin support in such a short timespan when we have been waiting for so long for other options is for me amazing.

This is the last piece of the puzzle for me to do a full containered repease pipeline for a project with multiple .net core microservices.

So it is very essential work (probably to many other people in the industry).

I honestly don’t know what im missing with the current implementation i just have a curiosity for what can be expected of any OSS project. 
The most important thing i usually find to be the creaters take on shortcommings or other compromises in the project - its really good to know so users can anticipate deadends and work around them early on if needed.

In short good work 👍

**Comment by ttutisani** [comment]
Thank you!
I'm not taking it as a criticism at all, trust me.

**Comment by ChristianPejrup** [comment]
Hi,
Is there anything left to do with Gherkin tables and logging before a new version of the library can be released ?

**Comment by ttutisani** [comment]
@csurfleet needs to open a PR with changes and that needs to be merged after review.
Previous merge was reverted due to build issues. Needs to be tried again.

**Comment by ChristianPejrup** [comment]
Ahh - thought with no new active issues being worked on and no open PR's that all of your guys work from last week was done.

Do you know if Feature.cs is in a state to be worked in?
- i would like to give it a go over with a bit of a refactor, there are a lot of things going on and i though the class might benefit from a split into something like Arrange - Act - Assert.
I will do a PR once @csurfleet is done with the tables implementation, so i don't end up causing two much grief on the merge/rebase...

**Comment by ttutisani** [comment]
Sure, curious to see what you can do there. Keep in mind that preference is to take it towards more readable and intuitive direction, rather than just refactor.

Anyway, I created the versions folder top level, files under it for each version, and linked it from the home page readme file. This should make dealing with versions and expectations easier.

**Comment by ttutisani** [comment]
FYI - I released version 1.1.
Table data support will have to go into next version - currently candidate for version 1.2.

**Comment by ChristianPejrup** [comment]
@ttutisani Cool thanks for the update 👍

**Comment by ttutisani** [comment]
I am closing this issue. If anybody is ever curious about the release schedules, there is enough information on this issue for now. Enough to read and digest.
