### ISSUE TITLE
ignoring or skipping a test

### ISSUE THREAD

**Issue by SDETRK** [ttutisani/Xunit.Gherkin.Quick#48]
Hi,
In specflow we can use the tag '@ignore' to skip a test. The use case for it, for example, if the test is failing for a known bug and you want to skip running it until the bug is closed. Are you going to support it?

**Comment by ttutisani** [comment]
Makes sense. Will be the first to pick up and work on.
ETA within my availability: couple of weeks. Max in a month it will be out.
Thanks for submitting the issue!

**Comment by SDETRK** [comment]
great thank you!

**Comment by ttutisani** [comment]
I have couple of questions about this, just to make up my mind:

Do you think the scenario should still be discovered and shown in the output? Or do you think that ignored scenario should behave like non-existing scenario? Please clarify.

I personally think the scenario should be discovered, and in the output the result should say "skipped", but I may change my mind if otherwise makes more sense.

**Comment by SDETRK** [comment]
The scenario should still be discovered, it exists but it shouldn't be executed

**Comment by csurfleet** [comment]
I agree - they should discover but show as ignored if possible

**Comment by ttutisani** [comment]
Good. Thanks you all for the input!
It seems it's absolutely doable, since Xunit has a way to skip the test with the reason.
I'm targeting to use that capability. Scenario will show up with yellow triangle in the test runner GUI. And in the output stream it will simply display a skip reason next to the scenario name.

Work is in progress: https://github.com/ttutisani/Xunit.Gherkin.Quick/compare/tagsImprovements?expand=1

I need to cleanup slightly how we handle tags in general, and then I will be able to add the capability to ignore the scenario based on the `@ignore` tag.

**Comment by ttutisani** [comment]
FYI - code changes are complete and merged.
I will write up some instructions and then will release.
That will be either tomorrow or next week.

**Comment by ttutisani** [comment]
Nuget version 3.1.0 is out now. That is for `@ignore` tag support.
If you face any issues, please let me know.

**Comment by SDETRK** [comment]
ok great, thank you!

**Comment by ttutisani** [comment]
Closing this issue. If any problems found, please open a new github issue.
