### ISSUE TITLE
Tests ignored in Visual Studio 2017/2019

### ISSUE THREAD

**Issue by PBarnard** [ttutisani/Xunit.Gherkin.Quick#86]
Hi there, I'm having trouble getting the tests running in Visual Studio, both 2017 and 2019. I've followed the Getting Started and the test is marked as "ignored" with the message 

"VsTest test case is missing. Rebuild the project and try again".

I've tried this person's repo and I get the same result:

https://github.com/sajohnstone/gurkin

![image](https://user-images.githubusercontent.com/14309231/61655873-536a9f80-acb7-11e9-9bf4-4278bc3b19b7.png)

**Comment by ttutisani** [comment]
@PBarnard this test runner does not look like standard visual studio runner. Is this ReSharper? Note that you need to use standard built-in test runner of visual studio and not ReSharper test runner.

I guess I need to mention it in the documentation since I've heard this complaint several times now.

Please confirm if this solves your issue.

**Comment by PBarnard** [comment]
Ahh yes, that was it, I was trying to run them in r#.

Cheers! 👍

**Comment by ttutisani** [comment]
No worries @PBarnard .

I am closing this ticket since I have also mentioned the workaround in the Getting Started document.
